# Generated by Django 5.1.6 on 2025-04-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='warn_on_task_section_delete',
            field=models.BooleanField(default=True, verbose_name='Предупреждать при удалении секции'),
        ),
    ]
