# Generated by Django 5.1.6 on 2025-04-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_usersettings_warn_on_task_section_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправление уведомлений по email'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая тема'), ('dark', 'Тёмная тема'), ('custom', 'Персонализированная тема')], default='light', max_length=10, verbose_name='Тема интерфейса'),
        ),
    ]
