# Generated by Django 5.1.6 on 2025-03-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='section',
            new_name='section_id',
        ),
    ]
