# Generated by Django 5.1.6 on 2025-04-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_task_deadline_task_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Крайний срок выполнения задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Крайнее время выполнения задачи'),
        ),
    ]
